image: Visual Studio 2017
version: 2.1.{build}
services:
  - mongodb
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: |
     cd src
     dotnet restore
     cd ..
environment:
  CODECOV_REPO_TOKEN:
    secure: YOcqTi+52nkE0y5alQZUbpo6rXiEsVuq3q4q+0pUQg08QM1Dwrss83m9BIxnFP1/
configuration:
  - Release
test_script:
  - dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="../../coverage/coverage.cobertura.xml" "src/MongoMigrations.Test/MongoMigrations.Test.csproj"
after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "coverage/coverage.cobertura.xml" -t $env:CODECOV_REPO_TOKEN
for:
-
  branches:
    only:
      - master

  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: lo9gC4NDoECBxAzgZZMFKklAQGmyL7VOIfMzPqRB1InlB4D5g4A+tSGUITR2pS6i
    skip_symbols: false
