image: Visual Studio 2022
version: 2.2.{build}
services:
  - mongodb
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: |
     cd src
     dotnet restore
     cd ..
environment:
  CODECOV_REPO_TOKEN:
    secure: YOcqTi+52nkE0y5alQZUbpo6rXiEsVuq3q4q+0pUQg08QM1Dwrss83m9BIxnFP1/
configuration:
  - Release
test_script:
  - dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput="../../coverage/coverage.cobertura.xml" "src/MongoMigrations.Test/MongoMigrations.Test.csproj"
after_test:
- ps: |
    $ProgressPreference = 'SilentlyContinue' 
    Invoke-WebRequest -Uri https://cli.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    $commit=git log --pretty=format:'%H' -n 1
    echo $commit
    # .\codecov.exe do-upload --commit-sha $commit -f "coverage/coverage.cobertura.xml" -t $env:CODECOV_REPO_TOKEN
on_finish:
- ps: $blockRdp=true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
for:
-
  branches:
    only:
      - master

  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: KqKTxwdbcvlB9Hp5+5rdk6nANSM4IAd+NKA+Ojik7d6eLk0/JGblNJlnUNXARmd5
    skip_symbols: false
